name: Shared CI

on:
  workflow_call:
    inputs:
      fetch-depth:
        required: false
        type: number
        default: 0
      run-audit-signatures:
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm clean-install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Check package contents
        run: npm run pack:check

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        if: ${{ inputs.run-audit-signatures }}
        run: npm audit signatures
